# https://aka.ms/yaml
jobs:
- job: build_all
  pool:
    vmImage: 'vs2017-win2016' # other options: 'macOS-10.13', 'ubuntu-16.04'
  timeoutInMinutes: 120
  strategy:
    matrix:
      x86-bits:
        arch: '32'
        build.set: 'all'
      x64-bits:
        arch: '64'
        build.set: 'all'
    maxParallel: 2
  steps:
  - template: azure/buildtemplate.yml

- job: build_micro
  pool:
    vmImage: 'vs2017-win2016' # other options: 'macOS-10.13', 'ubuntu-16.04'
  timeoutInMinutes: 120
  strategy:
    matrix:
      x86-microbits:
        arch: '32'
        build.set: 'micro'
      x64-microbits:
        arch: '64'
        build.set: 'micro'
    maxParallel: 2
  steps:
  - template: azure/buildtemplate.yml
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'klayout-$(build.set)bits-$(arch)'
      targetPath: 'klayout-bits-installed'

- job: aggregate_micro
  displayName: 'Aggregate KLayout microbits'
  dependsOn: build_micro
  pool:
    vmImage: 'vs2017-win2016' # other options: 'macOS-10.13', 'ubuntu-16.04'
  steps:
  - checkout: none
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'klayout-microbits-32'
      targetPath: $(System.DefaultWorkingDirectory)
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'klayout-microbits-64'
      targetPath: $(System.DefaultWorkingDirectory)
  - bash: |
      find .
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'klayout-microbits'
      targetPath: '$(System.DefaultWorkingDirectory)'

- job: aggregate_all
  displayName: 'Aggregate KLayout bits'
  dependsOn: build_all
  pool:
    vmImage: 'vs2017-win2016' # other options: 'macOS-10.13', 'ubuntu-16.04'
  steps:
  - checkout: none
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'klayout-allbits-32'
      targetPath: $(System.DefaultWorkingDirectory)
  - task: DownloadPipelineArtifact@0
    inputs:
      artifactName: 'klayout-allbits-64'
      targetPath: $(System.DefaultWorkingDirectory)
  - bash: |
      find .
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'klayout-bits'
      targetPath: '$(System.DefaultWorkingDirectory)'
