# https://aka.ms/yaml
jobs:
- job: Build
  pool:
    vmImage: 'vs2017-win2016' # other options: 'macOS-10.13', 'ubuntu-16.04'

  steps:
  - script: |
      pacman -S bison
    displayName: 'Installing dependencies'
  - script: |
      buildall.bat
    displayName: 'Build all bits'
